<?php

namespace Szymon\TurniejBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GrupaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupaRepository extends EntityRepository
{
	/**
	 * Wybierz wszystkie grupy dla danej rundy turnieju
	 * 
	 * @param Turniej $turniej
	 * @param int $runda
	 * @return array $grupy:
	 */
	public function findAllRunda($turniej, $runda) 
	{
		$query = $this->createQueryBuilder('g')
			->where('g.runda = :runda AND g.turniej = :turniej')
			->setParameter('runda', $runda)
			->setParameter('turniej', $turniej)
			->getQuery();
		
		return $query->getResult();
	}
	
	/**
	 * Get grupy for choice input
	 * 
	 * @param Turniej $turniej
	 * @return array $grupy:
	 */
	public function getGrupyChoices($turniej)
	{
		$query = $this->createQueryBuilder('g')
			->where('g.turniej = :turniej')
			->setParameter('turniej', $turniej)
			->getQuery();
		
		$grupy      = $query->getResult();
		$result     = array();
		$result[-1] = 'Wszystkie';
		
		foreach($grupy as $grupa) {
			$result[$grupa->getId()] = $grupa->getNazwaGrupy();
		}
		
		return $result;
	}
}