<?php

namespace Szymon\TurniejBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TurniejRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurniejRepository extends EntityRepository
{
}